apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: akademia-kc
spec:
  instances: 1
  image: quay.io/phasetwo/phasetwo-keycloak:23
  db:
    vendor: postgres
    host: akademia-db-postgres-do-user-16040512-0.c.db.ondigitalocean.com
    startOptimized: false
    usernameSecret:
      name: keycloak-db
      key: KC_DB_USERNAME
    passwordSecret:
      name: keycloak-db
      key: KC_DB_PASSWORD
    database: keycloak
    port: 25060
  http:
    httpEnabled: true
  hostname:
    hostname: auth.akademia.cc
    strict: false
    strictBackchannel: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
