apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  strategy: 
    type: "RollingUpdate"
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0
          args: ["start", "--cache-stack=kubernetes"]
          imagePullPolicy: "Always"
          env:
          - name: KEYCLOAK_ADMIN
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - name: KC_PROXY
            value: "edge"
          - name: jgroups.dns.query
            value: "keycloak"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_METRICS_ENABLED
            value: "true"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HTTP_RELATIVE_PATH
            value: "/"
          - name: KC_HOSTNAME_URL
            value: "http://10.244.0.130:8080/"
          - name: KC_HOSTNAME_ADMIN_URL
            value: "http://10.244.0.130:8080/realms/master/"
          - name: KC_DB
            value: "postgres"
          - name: KC_DB_URL
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL
          - name: KC_DB_URL_HOST
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_HOST
          - name: KC_DB_URL_PORT
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_PORT
          - name: KC_DB_URL_DATABASE
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_DATABASE
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_USERNAME
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080
            - name: jgroups
              containerPort: 7600
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"