apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: akademia-kc
spec:
  instances: 1
  image: quay.io/phasetwo/phasetwo-keycloak:23
  startOptimized: false
  db:
    vendor: postgres
    host: akademia-db-postgres-do-user-16040512-0.c.db.ondigitalocean.com
    usernameSecret:
      name: keycloak-db
      key: KC_DB_USERNAME
    passwordSecret:
      name: keycloak-db
      key: KC_DB_PASSWORD
    database: keycloak
    port: 25060
  http:
    httpEnabled: false
    httpsPort: 8443
    tlsSecret: keycloak-tls-secret
  ingress:
    enabled: false
  hostname:
    hostname: auth.akademia.cc
    admin: admin.auth.akademia.cc
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: proxy
      value: reencrypt
---   
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - auth.akademia.cc
      - admin.auth.akademia.cc
      secretName: keycloak-tls-secret
  rules:
  - host: auth.akademia.cc
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8443
  - host: admin.auth.akademia.cc
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-secret
  namespace: default
spec:
  secretName: keycloak-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.akademia.cc
    - admin.auth.akademia.cc