apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev"]
          env:
          - name: KEYCLOAK_ADMIN
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - name: KC_DB
            value: "postgres"
          - name: KC_PROXY
            value: "edge"
          - name: KC_DB_URL
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL
          - name: KC_DB_URL_HOST
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_HOST
          - name: KC_DB_URL_PORT
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_PORT
          - name: KC_DB_URL_DATABASE
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_URL_DATABASE
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_USERNAME
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: KC_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
