apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-secret
  namespace: default
spec:
  secretName: keycloak-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.akademia.cc
    - admin.auth.akademia.cc
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: akademia-kc
spec:
  instances: 1
  image: quay.io/phasetwo/phasetwo-keycloak:23
  startOptimized: false
  db:
    vendor: postgres
    host: akademia-db-postgres-do-user-16040512-0.c.db.ondigitalocean.com
    usernameSecret:
      name: keycloak-db
      key: KC_DB_USERNAME
    passwordSecret:
      name: keycloak-db
      key: KC_DB_PASSWORD
    database: keycloak
    port: 25060
  http:
    httpEnabled: true
  hostname:
    hostname: auth.akademia.cc
    admin: admin.auth.akademia.cc
    strict: false
    strictBackchannel: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    path: /
    pathType: ImplementationSpecific
    tls:
      - hosts:
          - auth.akademia.cc
          - admin.auth.akademia.cc
        secretName: keycloak-tls-secret
  proxy:
    headers: xforwarded
