apiVersion: apps/v1
kind: Deployment
metadata:
  name: akademia-collaboration
  namespace: default
  labels:
    app: collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration
  template:
    metadata:
      labels:
        app: collaboration
    spec:
      containers:
      - name: collaboration
        image: arctixdev/collaboration:latest
        ports:
        - containerPort: 8090
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: akademia-db
              key: DATABASE_URL
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collaboration-akademia-cc-tls
  namespace: default
spec:
  secretName: collaboration-akademia-cc-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - collaboration.akademia.cc
    - akademia-collaboration.arctix.dev
---
apiVersion: v1
kind: Service
metadata:
  name: akademia-collaboration-service
  namespace: default
spec:
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: collaboration
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  labels:
    app: collaboration
    app.kubernetes.io/instance: akademia-collaboration
  name: akademia-collaboration-ingress
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: akademia-collaboration-service
      port:
        number: 8090
  tls:
  - hosts:
    - collaboration.akademia.cc
    - akademia-collaboration.arctix.dev
    secretName: collaboration-akademia-cc-tls
  rules:
    - host: collaboration.akademia.cc
      http:
        paths:
          - backend:
              service:
                name: akademia-collaboration-service
                port:
                  number: 8090
            path: /
            pathType: Prefix
    - host: akademia-collaboration.arctix.dev
      http:
        paths:
          - backend:
              service:
                name: akademia-collaboration-service
                port:
                  number: 8090
            path: /
            pathType: Prefix
