apiVersion: apps/v1
kind: Deployment
metadata:
  name: akademia-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      # Mount the PVC
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: uptime-data-claim
      containers:
        - name: status
          image: louislam/uptime-kuma:latest
          # expose the container's port
          ports:
            - containerPort: 3001
          # Pass the mount into the container
          volumeMounts:
            - mountPath: '/app/data'
              name: data-mount
          # optional but recommended to set usage limits
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: akademia-status-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: status
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: uptime-data
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-data-claim
spec:
  storageClassName: uptime-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  labels:
    app: status
    app.kubernetes.io/instance: status
  name: status-ingress
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: status
      port:
        number: 3001
  rules:
    - host: status.akademia.cc
      http:
        paths:
          - backend:
              service:
                name: akademia-status-service
                port:
                  number: 3001
            path: /
            pathType: Prefix
    - host: akademia-status.arctix.dev
      http:
        paths:
          - backend:
              service:
                name: akademia-status-service
                port:
                  number: 3001
            path: /
            pathType: Prefix
  tls:
  - hosts:
    - status.akademia.cc
    - akademia-status.arctix.dev
    secretName: status-akademia-cc-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-akademia-cc-tls
  namespace: default
spec:
  secretName: status-akademia-cc-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - status.akademia.cc
    - akademia-status.arctix.dev
