apiVersion: apps/v1
kind: Deployment
metadata:
  name: akademia-api
  namespace: default
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: arctixdev/api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: akademia-db
              key: DATABASE_URL
        - name: OPENOBSERVE_USERNAME
          valueFrom:
            secretKeyRef:
              name: openobserve
              key: ZO_ROOT_USER_EMAIL
        - name: OPENOBSERVE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openobserve
              key: ZO_ROOT_USER_PASSWORD
        - name: ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: akademia-kc
              key: ADMIN_NAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akademia-kc
              key: ADMIN_PASSWORD
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-akademia-cc-tls
  namespace: default
spec:
  secretName: api-akademia-cc-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.akademia.cc
    - akademia-api.arctix.dev
---
apiVersion: v1
kind: Service
metadata:
  name: akademia-api-service
  namespace: default
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  labels:
    app: api
    app.kubernetes.io/instance: akademia-api
  name: akademia-api-ingress
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: akademia-api-service
      port:
        number: 3000
  tls:
  - hosts:
    - api.akademia.cc
    - akademia-api.arctix.dev
    secretName: api-akademia-cc-tls
  rules:
    - host: api.akademia.cc
      http:
        paths:
          - backend:
              service:
                name: akademia-api-service
                port:
                  number: 3000
            path: /
            pathType: Prefix
    - host: akademia-api.arctix.dev
      http:
        paths:
          - backend:
              service:
                name: akademia-api-service
                port:
                  number: 3000
            path: /
            pathType: Prefix
